id = "purosuco"
name = "PuroSuco"
version = "0.1.0"
schema_version = 1
authors = ["IgorPaslauski"]
description = "Suporte à linguagem PuroSuco"
repository = "https://github.com/IgorPaslauski/purosuco"

[grammars.purosuco]
repository = "https://github.com/IgorPaslauski/tree-sitter-purosuco"
rev = "main"
