id = "purosuco"
name = "PuroSuco"
version = "0.1.0"
schema_version = 1
authors = ["IgorPaslauski"]
description = "Suporte à linguagem PuroSuco"
repository = "https://github.com/IgorPaslauski/purosuco"

[grammars.purosuco]
repository = "https://github.com/IgorPaslauski/tree-sitter-purosuco"
rev = "a37841983dcfef4c8b0287b9fa92c12af7835a15"
